services:
  - type: web
    name: pharma-ai-webapp
    runtime: node
    plan: free
    region: ohio
    buildCommand: "npm install --legacy-peer-deps --production=false jspdf jspdf-autotable p-retry node-cache idb html2canvas && npm ci --legacy-peer-deps --ignore-engines --production=false && npx prisma generate && npm run build -- --no-lint"
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SKIP_BUILD_DATASET
        value: "1"
      - key: NEXT_PHASE
        value: phase-production-build
      - key: PYTHON_API_URL
        fromService:
          type: web
          name: pharma-ai-agent
          envVarKey: RENDER_EXTERNAL_URL
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: CLERK_SECRET_KEY
        value: sk_test_1JmmGgtIqwYNkUmEu3NY33mQ1s0pqJd6d9R5iqTRWJ
      - key: CLERK_PUBLISHABLE_KEY
        value: pk_test_cHJvbXB0LWFhcmR2YXJrLTMyLmNsZXJrLmFjY291bnRzLmRldiQ
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        value: pk_test_cHJvbXB0LWFhcmR2YXJrLTMyLmNsZXJrLmFjY291bnRzLmRldiQ
      - key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
        value: "/sign-in"
      - key: NEXT_PUBLIC_CLERK_SIGN_UP_URL
        value: "/sign-up"
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
        value: "/dashboard"
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
        value: "/dashboard"
      - key: CLERK_PRODUCTION_SESSION_DURATION
        value: "2d"
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_f7kebLD2AmiB@ep-late-sunset-a587ahwr-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require"
      - key: DIRECT_URL
        value: "postgresql://neondb_owner:npg_f7kebLD2AmiB@ep-late-sunset-a587ahwr-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require"
      - key: NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY
        value: pk_test_cfe48b571b61246b1fddda8e7a144c51dbf16069
      - key: PAYSTACK_SECRET_KEY
        value: sk_test_402c5b61c47453af64b3334c35bb1b31d3e7b7ba
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: pharma-ai-agent
          envVarKey: RENDER_EXTERNAL_URL
      - key: GROQ_API_KEY
        value: "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"
      - key: GROQ_BASE_URL
        value: "https://api.groq.com/openai/v1"
      - key: LLM_MODEL
        value: "llama3-8b-8192"
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: OPENAI_API_KEY
        value: "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"
    buildFilter:
      paths:
        - app/**
        - components/**
        - public/**
        - styles/**
        - lib/**
        - prisma/**
        - package.json
        - package-lock.json
        - next.config.mjs
        - tsconfig.json
        - middleware.ts
        - tailwind.config.ts
        - postcss.config.mjs