# Main render.yaml for the entire PharmaAI project
services:
  # Python Agent API
  - type: web
    name: pharma-ai-agent
    runtime: python
    plan: free
    region: ohio
    rootDir: agent
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_BASE_URL
        value: https://api.groq.com/openai/v1
      - key: LLM_MODEL
        value: llama3-8b-8192
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_BASE_URL
        value: https://api.groq.com/openai/v1

  # Next.js Frontend Application
  - type: web
    name: pharma-ai-webapp
    runtime: node
    plan: free
    region: ohio
    rootDir: pharma_app
    buildCommand: npm ci --legacy-peer-deps && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_API_URL
        fromService:
          type: web
          name: pharma-ai-agent
          envVarKey: RENDER_EXTERNAL_URL
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
        value: "/sign-in"
      - key: NEXT_PUBLIC_CLERK_SIGN_UP_URL
        value: "/sign-up"
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
        value: "/dashboard"
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
        value: "/dashboard"
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY
        sync: false
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: pharma-ai-agent
          envVarKey: RENDER_EXTERNAL_URL 