services:
  - type: web
    name: pharma-ai-agent
    runtime: python
    plan: free
    region: ohio
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_BASE_URL
        value: https://api.groq.com/openai/v1
      - key: LLM_MODEL
        value: llama3-8b-8192
      - key: DATABASE_URL
        sync: false 