services:
  - type: web
    name: pharma-ai-agent
    runtime: python
    plan: free
    region: ohio
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_BASE_URL
        value: https://api.groq.com/openai/v1
      - key: LLM_MODEL
        value: llama3-8b-8192
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_f7kebLD2AmiB@ep-late-sunset-a587ahwr-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require"
      - key: GROQ_API_KEY
        value: "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"
      - key: GROQ_BASE_URL
        value: https://api.groq.com/openai/v1 